-- Only in own disposable DB via test:s10. No live catalog/user mutations.
begin;
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'S10 invariant failed: %',label; end if;
 perform set_config('eventradar.s10_checks',(coalesce(nullif(current_setting('eventradar.s10_checks',true),''),'0')::integer+1)::text,true);
end $$;
do $$
declare owner uuid:=gen_random_uuid(); viewer uuid:=gen_random_uuid(); editor uuid:=gen_random_uuid(); regular uuid:=gen_random_uuid(); src uuid; s public.sources; other_source uuid;
 o uuid; other_o uuid; e uuid; other_e uuid; city uuid; claim uuid; document jsonb; batch jsonb; caught boolean; result jsonb; first_id uuid; second_id uuid;
begin
 insert into auth.users(id,email) values(owner,'admin-s10@fixture.invalid'),(viewer,'viewer-s10@fixture.invalid'),(editor,'editor-s10@fixture.invalid'),(regular,'regular-s10@fixture.invalid');
 perform public.set_s10_role(owner,'admin','Own synthetic bootstrap');perform public.set_s10_role(viewer,'viewer','Own synthetic viewer');perform public.set_s10_role(editor,'editor','Own synthetic editor');
 perform set_config('request.jwt.claim.sub',regular::text,true);
 caught:=false;begin perform public.s10_dashboard();exception when insufficient_privilege then caught:=true;end;perform pg_temp.check(caught,'nonadmin denied');
 perform pg_temp.check(not has_function_privilege('authenticated','public.set_s10_role(uuid,text,text)','execute'),'no client role grant');
 perform pg_temp.check(not has_table_privilege('authenticated','public.s10_roles','insert'),'no direct role escalation');
 perform pg_temp.check(not has_table_privilege('authenticated','public.s10_provider_facts','select'),'private provider baseline');
 perform set_config('request.jwt.claim.sub',owner::text,true);
 result:=public.s10_dashboard();perform pg_temp.check(result->>'role'='admin','admin dashboard works');
 perform pg_temp.check(result->'ai'->'settings'->'enabled'='false','AI disabled accurate');
 document:='{"code":"qa-source","name":"Synthetic source","url":"https://fixture.invalid/","acquisition":"api","terms_status":"unreviewed","rights_reference":"https://fixture.invalid/rights","allow_cache":false,"allow_translate":false,"allow_images":false,"poll_enabled":false,"poll_interval_seconds":3600,"freshness_seconds":7200,"coverage_note":"Explicit synthetic partial coverage"}';
 src:=public.s10_source(document,'Own synthetic creation');select * into s from public.sources where id=src;
 perform pg_temp.check(not s.poll_enabled and s.terms_status='unreviewed','new source disabled unreviewed');
 perform pg_temp.check(public.claim_s6_source('qa-source',true) is null,'unknown adapter never fetched');
 caught:=false;begin perform public.s10_source(document||'{"poll_enabled":true}','No reviewed adapter',src,1);exception when others then caught:=true;end;perform pg_temp.check(caught,'cannot activate arbitrary adapter');
 perform public.s10_source(document||'{"name":"Changed synthetic"}','Own synthetic update',src,1);
 caught:=false;begin perform public.s10_source(document,'Stale synthetic update',src,1);exception when serialization_failure then caught:=true;end;perform pg_temp.check(caught,'source optimistic conflict');
 perform set_config('request.jwt.claim.sub',viewer::text,true);
 perform pg_temp.check(public.s10_dashboard()->>'role'='viewer','viewer read');
 caught:=false;begin perform public.s10_source(document,'Viewer write denied');exception when insufficient_privilege then caught:=true;end;perform pg_temp.check(caught,'viewer source denied');
 perform set_config('request.jwt.claim.sub',editor::text,true);
 caught:=false;begin perform public.s10_source(document,'Editor source denied');exception when insufficient_privilege then caught:=true;end;perform pg_temp.check(caught,'editor registry denied');
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform public.s10_delete_source(src,2,'Delete own empty fixture');perform pg_temp.check(not exists(select 1 from public.sources where id=src),'empty deletion');
 insert into public.sources(code,name,url,acquisition,terms_status,rights_reference,allow_cache,last_success_at,poll_interval_seconds,coverage_note) values('madrid','Synthetic Madrid','https://datos.madrid.es/dataset/300107-0-agenda-actividades-eventos/information','api','allowed','https://fixture.invalid/rights',true,now(),86400,'Synthetic only') returning id into src;
 insert into public.territories(country_code,external_id,kind,names,provenance) values('ES','iso3166:ES','country','{"en":"Spain"}','Own synthetic geography') returning id into city;
 insert into public.territories(country_code,external_id,kind,parent_id,names,provenance) values('ES','madrid:municipio:Madrid','city',city,'{"en":"Madrid"}','Own synthetic geography') returning id into city;
 claim:=public.claim_s6_source('madrid',true);
 batch:=jsonb_build_array(jsonb_build_object('external_id','s10-fixture','hash',repeat('a',64),'title','Synthetic opera','description','Synthetic text','venue','Synthetic venue','url','https://www.madrid.es/s10-fixture','category_code','music','territory','madrid:municipio:Madrid','original_language','es','location',jsonb_build_array(-3.7,40.4),
 'occurrences',jsonb_build_array(jsonb_build_object('external_id','s10-fixture','time_kind','known','start_at',now()+interval '5 days','timezone','Europe/Madrid'))));
 perform public.ingest_s6_source('madrid',batch,now(),claim,'{}');
 select oc.id,ev.id into o,e from public.occurrences oc join public.events ev on ev.id=oc.event_id where ev.primary_source_id=src;
 perform set_config('request.jwt.claim.sub',editor::text,true);
 perform public.s10_correct(o,1,'{"title":"Corrected synthetic"}','Verified synthetic correction');
 perform pg_temp.check((select patch->>'title'='Corrected synthetic' from public.s8_corrections where occurrence_id=o),'persistent overlay');
 perform public.s10_correct(o,2,'{"category_code":null}','Explicit synthetic unknown categorization');
 perform pg_temp.check((select category_code is null from public.events where id=e),'manual categorization');
 perform public.s10_correct(o,3,'{"timezone":"UTC"}','Explicit synthetic timezone correction');
 perform public.ingest_madrid(jsonb_build_array((batch->0)||jsonb_build_object('locality','MADRID','occurrence',batch->0->'occurrences'->0)),now());
 perform pg_temp.check((select timezone='UTC' from public.occurrences where id=o),'legacy import preserves manual timezone');
 perform pg_temp.check((select title='Corrected synthetic' and category_code is null from public.events where id=e),'legacy preserves title and classification');
 caught:=false;begin perform public.s10_correct(o,1,'{"title":"Overwrite stale"}','Stale editor expected version');exception when serialization_failure then caught:=true;end;perform pg_temp.check(caught,'event optimistic conflict');
 perform pg_temp.check((select count(*)=3 and bool_and(actor=editor) from public.s10_audit where action='event_correct' and target=o),'actor audited');
 claim:=public.claim_s6_source('madrid',true);perform public.ingest_s6_source('madrid',batch,now(),claim,'{}');
 perform pg_temp.check((select title='Corrected synthetic' from public.events where id=e),'reimport preserves correction');
 perform pg_temp.check((select category_code is null from public.events where id=e),'reimport preserves categorization');
 perform public.s10_reset_override(o,(select version from public.events where id=e),'Reset to fresh source facts');
 perform pg_temp.check((select title='Synthetic opera' from public.events where id=e),'baseline restored');
 perform pg_temp.check((select category_code='music' from public.events where id=e),'baseline categorization restored');
 perform pg_temp.check(not exists(select 1 from public.s8_corrections where occurrence_id=o),'overlay removed');
 update public.s10_provider_facts set checked_at=now()-interval '10 days' where occurrence_id=o;
 caught:=false;begin perform public.s10_reset_override(o,(select version from public.events where id=e),'Reject stale baseline reset');exception when others then caught:=true;end;perform pg_temp.check(caught,'stale reset rejected');
 perform set_config('request.jwt.claim.sub',owner::text,true);
 select to_jsonb(ss)-array['id','last_success_at','is_demo','admin_revision'] into document from public.sources ss where id=src;
 claim:=public.claim_s6_source('madrid',true);
 perform public.s10_source(document||'{"poll_enabled":false}','Pause synthetic source',src,1);
 perform pg_temp.check(public.claim_s6_source('madrid',true) is null,'force cannot bypass disabled source');
 caught:=false;begin perform public.ingest_s6_source('madrid',batch,now(),claim,'{}');exception when others then caught:=true;end;perform pg_temp.check(caught,'outstanding fetch invalidated');
 caught:=false;begin perform public.ingest_madrid('[]',now());exception when others then caught:=true;end;perform pg_temp.check(caught,'legacy importer respects disable');
 caught:=false;begin perform public.s10_delete_source(src,2,'Referenced source not deleted');exception when others then caught:=true;end;perform pg_temp.check(caught,'provenance deletion denied');
 perform public.s10_source(document,'Resume synthetic source',src,2);
 claim:=public.claim_s6_source('madrid',true);perform public.fail_s6_source('madrid',claim,'fetch_failed');
 perform pg_temp.check(exists(select 1 from public.ingestion_runs where source_id=src and status='failed' and diagnostic->>'error_code'='fetch_failed'),'durable sanitized failure');
 update public.events set checked_at=now()-interval '10 days' where id=e;
 result:=public.s10_dashboard();perform pg_temp.check(result->'sources'->0->>'stale_records'='1','record stale visible');
 perform pg_temp.check(result->'sources'->0->>'last_error_code'='fetch_failed','source failure visible');
 insert into public.sources(name,url,acquisition,terms_status,allow_cache,last_success_at) values('Synthetic duplicate source','https://fixture.invalid/duplicate','api','allowed',true,now()) returning id into other_source;
 insert into public.events(primary_source_id,canonical_url,checked_at,title,venue,category_code,territory_id,original_language,location) select other_source,'https://fixture.invalid/duplicate',now(),title,venue,category_code,territory_id,original_language,location from public.events where id=e returning id into other_e;
 insert into public.occurrences(event_id,external_id,time_kind,start_at,timezone) select other_e,'duplicate',time_kind,start_at,timezone from public.occurrences where id=o returning id into other_o;
 first_id:=least(o,other_o);second_id:=greatest(o,other_o);
 insert into public.duplicate_candidates(left_occurrence,right_occurrence) values(first_id,second_id);
 insert into public.saved_events(user_id,occurrence_id) values(owner,o),(owner,other_o);
 perform public.s10_review_duplicate(first_id,second_id,o,(select ev.version from public.occurrences oc join public.events ev on ev.id=oc.event_id where oc.id=first_id),(select ev.version from public.occurrences oc join public.events ev on ev.id=oc.event_id where oc.id=second_id),'Confirmed same synthetic session');
 perform pg_temp.check(public.s10_group(other_o)=o,'logical merge');
 perform pg_temp.check((select count(*)=2 from public.saved_events where user_id=owner),'saved identities preserved');
 perform pg_temp.check(public.list_s5_events()->>'total'='1','catalog deduplicated before pagination');
 perform public.save_s4_rule(jsonb_build_object('name','Synthetic merged rule','enabled',true,'timezone','UTC','filters',jsonb_build_object('scope','s4','categories','[]'::jsonb,'languages','[]'::jsonb,'include_unknown_language',true,'include_unknown_price',true,'include_unknown_age',true),'event_horizon',jsonb_build_object('kind','days','days',30),'areas',jsonb_build_array(jsonb_build_object('kind','city','territory_id',city,'parameters','{}'::jsonb))));
 perform pg_temp.check((select count(*)=1 from public.s7_matches(owner,null,now())),'scheduler match union deduplicated');
 perform pg_temp.check(public.list_s5_events('matches')->>'total'='1','manual matches deduplicated');
 update public.sources set terms_status='blocked' where id=src;
 perform pg_temp.check((select count(*)=1 and bool_and(occurrence_id=other_o) from public.s7_matches(owner,null,now())),'eligible duplicate replaces rights-blocked primary');
 perform pg_temp.check(public.list_s5_events()->>'total'='1','catalog eligible fallback');
 update public.sources set terms_status='allowed' where id=src;
 update public.events set title='Different provider facts',version=version+1 where id=other_e;
 perform pg_temp.check(public.s10_group(other_o)=other_o,'provider divergence splits merge');
 perform pg_temp.check(public.list_s5_events()->>'total'='2','different sessions visible');
 perform public.s10_review_duplicate(first_id,second_id,null,(select ev.version from public.occurrences oc join public.events ev on ev.id=oc.event_id where oc.id=first_id),(select ev.version from public.occurrences oc join public.events ev on ev.id=oc.event_id where oc.id=second_id),'Undo synthetic logical merge');
 perform pg_temp.check(not exists(select 1 from public.s10_merges),'explicit undo');
 perform public.set_s10_role(owner,null,'Revoke own synthetic role');
 caught:=false;begin perform public.s10_dashboard();exception when insufficient_privilege then caught:=true;end;perform pg_temp.check(caught,'revocation applies without new JWT');
 delete from auth.users where id=owner;
 perform pg_temp.check(not exists(select 1 from public.s10_audit where actor=owner or target=owner),'account deletion removes audit identifiers');
end $$;
select jsonb_build_object('invariant_checks',current_setting('eventradar.s10_checks')::integer);
rollback;
