-- Synthetic fixtures only; run in the schema-only disposable DB created by test:s7.
begin;
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'S7 invariant failed: %',label; end if;
 perform set_config('eventradar.s7_checks',(coalesce(nullif(current_setting('eventradar.s7_checks',true),''),'0')::integer+1)::text,true);
 raise notice 'PASS %',label;
end $$;
do $$
declare owner uuid:=gen_random_uuid(); src uuid; city uuid; event uuid; occurrence uuid; rule uuid; second_rule uuid;
 d jsonb:='{"mode":"daily","active":true,"time":"18:00"}'; result jsonb; first_digest uuid; job uuid; claim jsonb; device uuid; dispatched jsonb; n integer; caught boolean;
begin
 perform pg_temp.check(public.s7_local_instant('2027-03-28 02:30','Europe/Madrid')='2027-03-28 01:00Z'::timestamptz,'Madrid spring gap -> 03:00 local');
 perform pg_temp.check(public.s7_local_instant('2027-10-31 02:30','Europe/Madrid')='2027-10-31 00:30Z'::timestamptz,'Madrid fold -> first instant');
 perform pg_temp.check(public.s7_next_run('{"mode":"daily","active":true,"time":"02:30"}','Europe/Madrid','2027-10-31 00:40Z')='2027-11-01 01:30Z'::timestamptz,'Fold executes once');
 perform pg_temp.check(public.s7_local_instant('2027-03-14 02:30','America/Toronto')='2027-03-14 07:00Z'::timestamptz,'Toronto spring gap');
 perform pg_temp.check(public.s7_local_instant('2027-11-07 01:30','America/Toronto')='2027-11-07 05:30Z'::timestamptz,'Toronto fold');
 perform pg_temp.check(public.s7_local_instant('2011-12-30 10:00','Pacific/Apia')='2011-12-30 10:00Z'::timestamptz,'Skipped calendar date -> next available midnight');
 perform pg_temp.check(public.s7_next_run('{"mode":"weekdays","active":true,"time":"10:00","weekdays":[1,5]}','UTC','2027-03-29 10:00Z')='2027-04-02 10:00Z'::timestamptz,'Selected weekdays');
 perform pg_temp.check(public.s7_next_run('{"mode":"interval","active":true,"time":"18:00","days":2,"anchor":"2027-03-27"}','Europe/Madrid','2027-03-27 17:01Z')='2027-03-29 16:00Z'::timestamptz,'Calendar days preserve local time across DST');
 perform pg_temp.check(public.s7_next_run('{"mode":"interval","active":true,"time":"18:00","days":7,"anchor":"2030-01-01"}','UTC','2027-01-01 00:00Z')='2030-01-01 18:00Z'::timestamptz,'Future anchor preserved');
 perform pg_temp.check(public.s7_quiet_until('{"start":"22:00","end":"02:30"}','Europe/Madrid','2027-03-28 00:30Z')='2027-03-28 01:00Z'::timestamptz,'Quiet end spring gap');
 perform pg_temp.check(public.s7_quiet_until('{"start":"22:00","end":"02:30"}','Europe/Madrid','2027-10-31 01:10Z')='2027-10-31 01:30Z'::timestamptz,'Quiet end later fold');
 perform pg_temp.check(public.s7_next_run(d||'{"active":false}','UTC',now()) is null,'Inactive schedule');
 perform pg_temp.check((select hi from public.s7_horizon_bounds('{"kind":"months","months":1}','2027-01-31'))='2027-02-28'::date,'Calendar month end');
 perform pg_temp.check((select lo from public.s7_horizon_bounds('{"kind":"weekend"}','2027-04-04'))='2027-04-03'::date,'Sunday belongs to current weekend');
 insert into auth.users(id,email) values(owner,'s7-fixture-'||owner||'@fixture.invalid');
 insert into public.territories(country_code,external_id,kind,names,provenance) values('ZZ','s7-fixture-'||owner,'city','{"en":"Synthetic S7 city"}','synthetic S7') returning id into city;
 insert into public.sources(name,url,acquisition,terms_status,allow_cache,last_success_at) values('S7 synthetic','https://fixture.invalid/','fixture','allowed',true,now()) returning id into src;
 insert into public.events(primary_source_id,canonical_url,checked_at,title,territory_id) values(src,'https://fixture.invalid/s7',now(),'Synthetic S7 event',city) returning id into event;
 insert into public.occurrences(event_id,external_id,time_kind,start_at,timezone) values(event,'s7-fixture','known',now()+interval '2 days','UTC') returning id into occurrence;
 insert into public.rules(user_id,name,enabled,filters,event_horizon,timezone,delivery_schedule) values(owner,'S7 A',true,
 '{"scope":"s4","categories":[],"languages":[],"include_unknown_language":true,"include_unknown_price":true,"include_unknown_age":true}',
 '{"kind":"days","days":14}','UTC',d) returning id into rule;
 insert into public.rule_areas(rule_id,user_id,kind,territory_id) values(rule,owner,'city',city);
 insert into public.rules(user_id,name,enabled,filters,event_horizon,timezone,delivery_schedule) select user_id,'S7 B',enabled,filters,event_horizon,timezone,delivery_schedule from public.rules where id=rule returning id into second_rule;
 insert into public.rule_areas(rule_id,user_id,kind,territory_id) values(second_rule,owner,'city',city);
 perform pg_temp.check((select next_run_at>now() from public.rules where id=rule),'Next run persisted');
 update public.rules set next_run_at=now()-interval '1 minute' where user_id=owner;
 result:=public.run_s7_scheduler();first_digest:=(result->>'digest_id')::uuid;
 perform pg_temp.check(result->>'status'='ready' and result->>'items'='1','Full union without duplicate cards');
 perform pg_temp.check((select cardinality(matched_rule_names)=2 and selection_snapshot->>'title'='Synthetic S7 event' from public.digest_items where digest_id=first_digest),'Immutable full item/rule snapshot');
 perform pg_temp.check(public.run_s7_scheduler()->>'status'='idle','Retry/restart produces one logical digest');
 perform pg_temp.check((select count(*)=1 from public.digests where user_id=owner),'One digest per due run');
 claim:=public.claim_s7_notification();
 perform pg_temp.check(claim->>'status'='opt_out','Inbox works without push permission');
 update public.rules set next_run_at=now()-interval '2 minutes' where user_id=owner;
 result:=public.run_s7_scheduler();
 perform pg_temp.check(result->>'status'='ready' and result->>'notify'='false','Unchanged selection still in history without duplicate push');
 perform pg_temp.check((select count(*)=2 from public.digests where user_id=owner),'Every non-empty due selection retained');
 update public.events set checked_at=now()-interval '3 days' where id=event;
 update public.rules set next_run_at=now()-interval '3 minutes' where user_id=owner;
 result:=public.run_s7_scheduler();
 perform pg_temp.check(result->>'status'='stale','Record TTL enforced even with fresh source');
 perform pg_temp.check((select bool_and(schedule_retry_at>now() and next_run_at<now()) from public.rules where user_id=owner),'Stale retry keeps original business slot');
 perform pg_temp.check(public.run_s7_scheduler()->>'status'='idle','Stale backoff avoids hot loop');
 update public.events set checked_at=now(),version=version+1 where id=event;
 update public.rules set schedule_retry_at=now()-interval '1 second' where user_id=owner;
 result:=public.run_s7_scheduler();
 perform pg_temp.check(result->>'status'='ready' and result->>'notify'='true','Fresh changed event resumes deferred run');
 perform pg_temp.check((select count(*)=1 from public.s7_runs where user_id=owner and outcome='ready' and scheduled_at=now()-interval '3 minutes'),'Stale journal updated to ready');
 update public.profiles set push_enabled=true where id=owner;
 insert into public.device_tokens(user_id,token,platform) values(owner,'ExpoPushToken[s7synthetic123456789]','ios') returning id into device;
 claim:=public.claim_s7_notification();job:=(claim->>'id')::uuid;
 perform pg_temp.check(claim->>'status'='claimed','Notification claim');
 dispatched:=public.begin_s7_delivery(job,(claim->>'token')::uuid,device);
 perform pg_temp.check(dispatched->>'status'='dispatch','One fenced dispatch');
 perform pg_temp.check(public.begin_s7_delivery(job,(claim->>'token')::uuid,device)->>'status'='already_attempted','No repeated device attempt');
 update public.notification_jobs set lease_until=now()-interval '1 second' where id=job;
 claim:=public.claim_s7_notification();
 perform pg_temp.check((select status='uncertain' from public.deliveries where id=(dispatched->>'delivery_id')::uuid),'Crash after dispatch preserves ambiguity');
 perform pg_temp.check(public.begin_s7_delivery(job,(claim->>'token')::uuid,device)->>'status'='already_attempted','Restart does not resend unknown push');
 perform pg_temp.check(public.finish_s7_notification(job,(claim->>'token')::uuid),'Restart completes remaining job');
 -- New version yields a new notification, and a definite ticket rejection may retry.
 update public.events set version=version+1 where id=event;
 update public.rules set next_run_at=now()-interval '4 minutes' where user_id=owner;
 result:=public.run_s7_scheduler();claim:=public.claim_s7_notification();job:=(claim->>'id')::uuid;
 dispatched:=public.begin_s7_delivery(job,(claim->>'token')::uuid,device);
 perform public.finish_s7_delivery((dispatched->>'delivery_id')::uuid,(claim->>'token')::uuid,'retry',null,'MessageRateExceeded');
 perform public.finish_s7_notification(job,(claim->>'token')::uuid);
 perform pg_temp.check((select status='pending' and run_at>now() from public.notification_jobs where id=job),'Sequential exponential backoff');
 update public.notification_jobs set run_at=now()-interval '1 second' where id=job;
 claim:=public.claim_s7_notification();dispatched:=public.begin_s7_delivery(job,(claim->>'token')::uuid,device);
 perform pg_temp.check(dispatched->>'status'='dispatch','Definite rejected attempt can retry');
 perform public.finish_s7_delivery((dispatched->>'delivery_id')::uuid,(claim->>'token')::uuid,'accepted','synthetic-receipt');
 perform public.finish_s7_notification(job,(claim->>'token')::uuid);
 perform pg_temp.check((select next_receipt_at=now()+interval '15 minutes' from public.deliveries where id=(dispatched->>'delivery_id')::uuid),'Receipt waits 15 minutes');
 perform public.finish_s7_receipt((dispatched->>'delivery_id')::uuid,'missing');
 perform pg_temp.check((select status='accepted' and receipt_attempts=1 from public.deliveries where id=(dispatched->>'delivery_id')::uuid),'Missing receipt retries query, never push');
 perform public.finish_s7_receipt((dispatched->>'delivery_id')::uuid,'error','DeviceNotRegistered');
 perform pg_temp.check(not exists(select 1 from public.device_tokens where id=device),'Invalid token removed');
 -- A late invalid receipt must not remove a more recently re-registered token.
 insert into public.device_tokens(user_id,token,platform,updated_at) values(owner,'ExpoPushToken[s7ReRegistered12345]','ios',now()+interval '1 second') returning id into device;
 insert into public.deliveries(job_id,user_id,device_token_id,status,dispatch_token,dispatched_at,receipt_id)
 values(job,owner,device,'accepted',gen_random_uuid(),now()-interval '1 second','old-receipt') returning id into first_digest;
 perform public.finish_s7_receipt(first_digest,'error','DeviceNotRegistered');
 perform pg_temp.check(exists(select 1 from public.device_tokens where id=device),'Late invalid receipt preserves fresh registration');
 update public.deliveries set status='accepted',dispatched_at=now()-interval '25 hours' where id=first_digest;
 perform public.finish_s7_receipt(first_digest,'missing');
 perform pg_temp.check((select status='receipt_unknown' from public.deliveries where id=first_digest),'Receipt expiry does not claim delivery success');
 -- A rule edit/area edit invalidates outstanding sends, but never deletes history.
 update public.events set version=version+1 where id=event;
 update public.rules set next_run_at=now()-interval '5 minutes' where user_id=owner;
 result:=public.run_s7_scheduler();
 update public.rules set timezone='America/Toronto' where id=rule;
 perform pg_temp.check((select next_run_at>now() from public.rules where id=rule),'Timezone edit reschedules');
 perform pg_temp.check(public.claim_s7_notification()->>'status'='rule_changed','Old job cancelled after rule edit');
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform public.set_s4_rule_enabled(rule,false);
 perform pg_temp.check((select next_run_at is null from public.rules where id=rule),'Rule pause clears next run');
 caught:=false;begin perform public.set_s7_delivery_preferences(rule,d||'{"quiet":{"start":"22:00","end":"22:00"}}','UTC');exception when others then caught:=true;end;
 perform pg_temp.check(caught,'Reject whole-day ambiguous quiet range');
 perform public.set_s7_delivery_preferences(second_rule,d||jsonb_build_object('quiet',jsonb_build_object('start',to_char(now() at time zone 'UTC'-interval '1 hour','HH24:MI'),'end',to_char(now() at time zone 'UTC'+interval '1 hour','HH24:MI'))),'UTC');
 update public.rules set next_run_at=now()-interval '6 minutes' where id=second_rule;
 result:=public.run_s7_scheduler();
 -- repeat_unchanged ensures a real pending quiet job for this synthetic test.
 update public.notification_jobs set status='pending' where digest_id=(result->>'digest_id')::uuid;
 perform pg_temp.check(public.claim_s7_notification()->>'status'='quiet','Quiet hours defer transport only');
 perform pg_temp.check(exists(select 1 from public.digest_items where digest_id=(result->>'digest_id')::uuid),'Quiet selection immediately available in inbox');
 -- Source permission and area edits are rechecked even after a successful claim.
 perform public.set_s7_delivery_preferences(second_rule,d,'UTC');
 update public.events set version=version+1 where id=event;
 update public.rules set next_run_at=now()-interval '8 minutes' where id=second_rule;
 result:=public.run_s7_scheduler();claim:=public.claim_s7_notification();job:=(claim->>'id')::uuid;
 update public.sources set terms_status='blocked' where id=src;
 perform pg_temp.check(public.begin_s7_delivery(job,(claim->>'token')::uuid,device)->>'status'='selection_unavailable','Permission checked immediately before dispatch');
 update public.sources set terms_status='allowed' where id=src;
 update public.rule_areas set parameters='{}' where rule_id=second_rule;
 perform pg_temp.check(public.begin_s7_delivery(job,(claim->>'token')::uuid,device)->>'status'='rule_changed','Area edit invalidates already claimed job');
 perform public.finish_s7_notification(job,(claim->>'token')::uuid);
 update public.events set status='cancelled' where id=event;
 update public.rules set next_run_at=now()-interval '7 minutes' where id=second_rule;
 result:=public.run_s7_scheduler();
 perform pg_temp.check(result->>'status'='empty','Empty match advances schedule without push');
 perform set_config('role','authenticated',true);
 select count(*) into n from public.digests where user_id=owner;
 perform pg_temp.check(n>0,'Owner reads history without device');
 caught:=false;begin perform public.run_s7_scheduler();exception when insufficient_privilege then caught:=true;end;
 perform pg_temp.check(caught,'Client cannot schedule jobs');
 caught:=false;begin perform public.claim_s7_notification();exception when insufficient_privilege then caught:=true;end;
 perform pg_temp.check(caught,'Client cannot claim sends');
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 perform pg_temp.check(not exists(select 1 from public.digests where user_id=owner),'Foreign history hidden');
 perform pg_temp.check(not exists(select 1 from public.s7_runs where user_id=owner),'Foreign run journal hidden');
 perform set_config('role','postgres',true);
end $$;
select jsonb_build_object('invariant_checks',current_setting('eventradar.s7_checks')::integer,'synthetic',true,'expo_requests',0);
rollback;
