-- Synthetic subscriptions and catalog; only own schema-only DB via test:s9.
begin;
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$ begin
 if ok is distinct from true then raise exception 'S9 invariant failed: %',label; end if;
 perform set_config('eventradar.s9_checks',(coalesce(nullif(current_setting('eventradar.s9_checks',true),''),'0')::integer+1)::text,true);
end $$;
do $$
declare owner uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); src uuid; e uuid; o uuid; ids uuid[]:='{}'; id uuid;
 doc jsonb; q jsonb; snapshot jsonb; previous_generation bigint; state jsonb; caught boolean; count_rules integer;
begin
 insert into auth.users(id,email) values(owner,'s9-synthetic@fixture.invalid'),(other,'s9-other@fixture.invalid');
 insert into public.sources(name,url,acquisition,terms_status,allow_cache,last_success_at) values('Synthetic S9','https://fixture.invalid','fixture','allowed',true,now()) returning public.sources.id into src;
 insert into public.events(primary_source_id,canonical_url,checked_at,title,location) values(src,'https://fixture.invalid/s9',now(),'Synthetic billing event',extensions.st_setsrid(extensions.st_makepoint(0,0),4326)) returning public.events.id into e;
 insert into public.occurrences(event_id,external_id,time_kind,start_at,timezone) values(e,'s9-fixture','known',now()+interval '2 days','UTC') returning public.occurrences.id into o;
 doc:='{"name":"Synthetic S9","enabled":true,"timezone":"UTC","filters":{"scope":"s4","categories":[],"languages":[],"include_unknown_language":true,"include_unknown_price":true,"include_unknown_age":true},"event_horizon":{"kind":"days","days":30},"areas":[{"kind":"radius","parameters":{"longitude":0,"latitude":0,"meters":1000}}]}'::jsonb;
 perform set_config('request.jwt.claim.sub',owner::text,true);
 for n in 1..12 loop id:=public.save_s4_rule(doc);ids:=array_append(ids,id);end loop;
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check(public.s9_tier(owner)='free','default disabled is Free');
 perform pg_temp.check((select count(*)=1 from public.rules where user_id=owner and public.s9_rule_allowed(public.rules.id)),'Free one effective rule');
 perform pg_temp.check((select count(*)=1 from public.s7_matches(owner,null,now())),'matching cannot bypass Free limit');
 perform pg_temp.check((select count(*)=11 from public.rules where user_id=owner and billing_paused),'extra rules persisted paused');
 perform public.choose_s9_free_rule(ids[2]);
 perform pg_temp.check(public.s9_rule_allowed(ids[2]),'explicit Free choice');
 perform pg_temp.check((select count(*)=12 from public.rules where user_id=owner and enabled),'intent and configs preserved');
 perform set_config('request.jwt.claim.sub',other::text,true);
 caught:=false;begin perform public.choose_s9_free_rule(ids[2]);exception when others then caught:=true;end;
 perform pg_temp.check(caught,'cross owner choice rejected');
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform public.set_s7_delivery_preferences(ids[2],'{"mode":"daily","active":true,"time":"18:00"}','UTC');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check(not public.s9_rule_allowed(ids[2]),'daily monitoring requires Plus');
 perform pg_temp.check((select next_run_at is null and billing_paused from public.rules where public.rules.id=ids[2]),'paused schedule has no due date');
 perform public.set_s7_delivery_preferences(ids[2],'{"mode":"weekdays","weekdays":[1],"active":true,"time":"18:00"}','UTC');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check(public.s9_rule_allowed(ids[2]),'weekly monitoring is Free');
 perform public.set_s7_delivery_preferences(ids[2],'{"mode":"weekdays","weekdays":[1,2],"active":true,"time":"18:00"}','UTC');
 perform pg_temp.check(not public.s9_rule_allowed(ids[2]),'multiple weekdays require Plus');
 perform public.set_s7_delivery_preferences(ids[2],'{"mode":"manual","active":false}','UTC');
 update public.rules set filters=filters||'{"languages":["en"]}' where public.rules.id=ids[2];
 perform pg_temp.check(not public.s9_rule_allowed(ids[2]),'additional language filter requires Plus');
 update public.rules set filters=filters-'languages'||'{"languages":[]}' where public.rules.id=ids[2];
 perform pg_temp.check(not public.request_s9_reconcile(),'disabled reconcile performs no provider request');
 update public.s9_config set enabled=true,entitlement_id='fixture-plus',product_ids=array['fixture-month'],app_ids=array['fixture-app'];
 caught:=false;begin update public.s9_config set entitlement_id=null;exception when check_violation then caught:=true;end;
 perform pg_temp.check(caught,'enabled configuration rejects NULL identifier');
 caught:=false;begin update public.s9_config set product_ids=array[null::text];exception when check_violation then caught:=true;end;
 perform pg_temp.check(caught,'enabled configuration rejects NULL product');
 perform pg_temp.check(public.enqueue_s9_reconcile(owner,'fixture-webhook'),'first webhook durable');
 previous_generation:=(select generation from public.s9_reconcile_queue where user_id=owner);
 perform pg_temp.check(not public.enqueue_s9_reconcile(owner,'fixture-webhook'),'duplicate webhook ignored');
 perform pg_temp.check((select generation=previous_generation from public.s9_reconcile_queue where user_id=owner),'duplicate generation unchanged');
 q:=public.claim_s9_reconcile();perform pg_temp.check(q->>'status'='claimed','provider refresh claim '||q::text);
 perform pg_temp.check(public.claim_s9_reconcile()->>'status'='idle','one fetch per owner');
 snapshot:=jsonb_build_object('tier','plus','expires_at',now()+interval '2 days','grace_until',null,'observed_at',now(),'environment','SANDBOX');
 perform pg_temp.check(not public.finish_s9_reconcile(owner,gen_random_uuid(),snapshot),'forged/lost claim rejected');
 perform public.enqueue_s9_reconcile(owner,'during-fetch');
 perform pg_temp.check(public.finish_s9_reconcile(owner,(q->>'claim')::uuid,snapshot),'verified snapshot accepted');
 perform pg_temp.check((select due_at<=now() from public.s9_reconcile_queue where user_id=owner),'event received during fetch stays pending');
 perform pg_temp.check(public.s9_tier(owner)='plus','verified Plus');
 perform pg_temp.check((select count(*)=10 from public.rules where user_id=owner and public.s9_rule_allowed(public.rules.id)),'Plus maximum ten effective rules');
 perform pg_temp.check((select count(*)=10 from public.s7_matches(owner,null,now())),'direct matching maximum ten');
 q:=public.claim_s9_reconcile();
 perform public.finish_s9_reconcile(owner,(q->>'claim')::uuid,jsonb_build_object('tier','free','observed_at',now()-interval '1 second','environment','SANDBOX'));
 perform pg_temp.check(public.s9_tier(owner)='plus','older provider response cannot revoke newer Plus');
 update public.entitlements set expires_at=now()-interval '1 second',grace_until=now()+interval '1 day' where user_id=owner;
 perform pg_temp.check(public.s9_tier(owner)='plus','grace access preserved');
 update public.entitlements set grace_until=now()-interval '1 second' where user_id=owner;
 perform pg_temp.check(public.s9_tier(owner)='free','expiry enforced without webhook');
 state:=public.s9_state();
 perform pg_temp.check(jsonb_array_length(state->'active_rules')=1,'downgrade leaves one effective rule');
 perform pg_temp.check((select count(*)=12 from public.rules where user_id=owner),'downgrade deletes no rules');
 perform pg_temp.check((select count(*)=11 from public.rules where user_id=owner and billing_paused),'downgrade persists pause');
 perform pg_temp.check((select count(*)=0 from public.rules where user_id=owner and billing_paused and next_run_at is not null),'paused rules have no schedule');
 insert into public.saved_events(user_id,occurrence_id) values(owner,o);
 perform public.correct_s8_occurrence(o,'{"status":"cancelled"}','Synthetic Free cancellation');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.check((select count(*)=1 from public.s8_alerts where user_id=owner and kind='cancelled'),'saved cancellation remains Free');
 perform pg_temp.check(public.run_s8_scheduler()->>'status'='published','Free cancellation reaches inbox');
 perform pg_temp.check((select count(*)=1 from public.saved_events where user_id=owner),'saved event remains after downgrade');
 update public.s9_reconcile_queue set due_at=now() where user_id=owner;q:=public.claim_s9_reconcile();
 perform pg_temp.check(public.fail_s9_reconcile(owner,(q->>'claim')::uuid),'provider error persisted retry');
 perform pg_temp.check((select due_at>now() and lease_until is null and error_code='provider_unavailable' from public.s9_reconcile_queue where user_id=owner),'bounded retry');
 perform pg_temp.check(not has_function_privilege('authenticated','public.finish_s9_reconcile(uuid,uuid,jsonb)','EXECUTE'),'client cannot apply entitlement');
 perform pg_temp.check(not has_table_privilege('authenticated','public.s9_config','SELECT'),'provider config private');
 perform pg_temp.check(not has_column_privilege('authenticated','public.rules','billing_paused','UPDATE'),'client cannot forge pause column');
 perform pg_temp.check(not has_function_privilege('authenticated','public.build_s3_digest(uuid)','EXECUTE'),'legacy bypass closed');
end $$;
select jsonb_build_object('invariant_checks',current_setting('eventradar.s9_checks')::integer,'store_purchases_verified',false,'provider_requests',0);
rollback;
