import { useEffect, useRef, useState } from 'react';
import { Text, View } from 'react-native';
import { Map, Camera, GeoJSONSource, Layer, type CameraRef, type GeoJSONSourceRef } from '@maplibre/maplibre-react-native';
import { eventFeatures, coordinates, mapStyle, draftFeatures, type EventMapProps } from '@/lib/discovery';
import { useLanguage } from '@/lib/i18n';
import { ui } from './screen';
import { Button } from './ui/button';
export function EventMap({items,onSelect,focus,draft,meters,onPoint}:EventMapProps){
 const{t}=useLanguage();const camera=useRef<CameraRef>(null);const source=useRef<GeoJSONSourceRef>(null);const[failed,setFailed]=useState(false);const[revision,setRevision]=useState(0);const point=focus??items.map(coordinates).find(Boolean)??[-3.7,40.42];
 useEffect(()=>{if(focus)void camera.current?.setStop({center:focus,duration:0}).catch(()=>setFailed(true));},[focus?.[0],focus?.[1]]);
 return <View style={{gap:8}}><Map key={revision} style={{height:340,width:'100%'}} mapStyle={mapStyle} onPress={e=>{if(onPoint&&e.nativeEvent.lngLat)onPoint(e.nativeEvent.lngLat);}} onDidFailLoadingMap={()=>setFailed(true)} onDidFinishLoadingMap={()=>setFailed(false)}><Camera ref={camera} initialViewState={{center:point,zoom:8}}/><GeoJSONSource ref={source} id="events" data={eventFeatures(items)} cluster clusterRadius={45} clusterMaxZoom={16} onPress={async(e)=>{const feature=e.nativeEvent.features[0];if(!feature)return;const p=feature.properties;if(p?.cluster_id!==undefined&&feature.geometry.type==='Point'){try{const zoom=await source.current?.getClusterExpansionZoom(Number(p.cluster_id));if(zoom)await camera.current?.setStop({center:feature.geometry.coordinates as [number,number],zoom});}catch{setFailed(true);}}else if(typeof p?.id==='string')onSelect(p.id);}}><Layer id="clusters" type="circle" filter={['has','point_count']} paint={{'circle-color':'#264c2c','circle-radius':20}}/><Layer id="cluster-label" type="symbol" filter={['has','point_count']} layout={{'text-field':['get','point_count_abbreviated'],'text-size':13,'text-font':['Noto Sans Regular']}} paint={{'text-color':'#fff'}}/><Layer id="points" type="circle" filter={['!', ['has','point_count']]} paint={{'circle-color':'#e1623d','circle-radius':8,'circle-stroke-width':2,'circle-stroke-color':'#fff'}}/></GeoJSONSource>{draft&&<GeoJSONSource id="draft" data={draftFeatures(draft,meters)}><Layer id="draft-fill" type="fill" filter={['==',['geometry-type'],'Polygon']} paint={{'fill-color':'#739654','fill-opacity':0.25}}/><Layer id="draft-line" type="line" filter={['!=',['geometry-type'],'Point']} paint={{'line-color':'#416b2b','line-width':2}}/><Layer id="draft-points" type="circle" filter={['==',['geometry-type'],'Point']} paint={{'circle-color':'#203b16','circle-radius':5,'circle-stroke-color':'#fff','circle-stroke-width':2}}/></GeoJSONSource>}</Map>{failed&&<><Text accessibilityRole="alert" style={ui.text}>{t('mapUnavailable')}</Text><Button label={t('retry')} onPress={()=>setRevision(v=>v+1)}/></>}</View>;
}
