import test from 'node:test';
import assert from 'node:assert/strict';
import {authorizedWebhook,webhookOwners,subscriberSnapshot,reconcileOne} from './lib/s9-revenuecat.mjs';
const config={enabled:true,app_ids:['fixture-app'],product_ids:['fixture-month'],entitlement_id:'fixture-plus',environment:'SANDBOX'};
const now=Date.now();
function body(expiry=now+100000){return {request_date_ms:now,subscriber:{entitlements:{'fixture-plus':{expires_date:new Date(expiry).toISOString(),grace_period_expires_date:null,product_identifier:'fixture-month'}},subscriptions:{'fixture-month':{store:'app_store',is_sandbox:true,refunded_at:null}}}};}
test('webhook authentication rejects missing/wrong auth',()=>{assert.equal(authorizedWebhook(undefined,'fixture'),false);assert.equal(authorizedWebhook('wrong','fixture'),false);assert.equal(authorizedWebhook('fixture','fixture'),true);});
test('only allowlisted app/environment; transfer reconciles both owners, including missing environment',()=>{const a='10000000-0000-0000-0000-000000000001',b='10000000-0000-0000-0000-000000000002';const event={id:'fixture',type:'TRANSFER',app_id:'fixture-app',environment:'SANDBOX',transferred_from:[a],transferred_to:[b,b]};assert.deepEqual(webhookOwners({event},config).owners,[a,b]);assert.deepEqual(webhookOwners({event:{...event,environment:undefined}},config).owners,[a,b]);assert.throws(()=>webhookOwners({event:{...event,environment:'PRODUCTION'}},config));assert.throws(()=>webhookOwners({event:{...event,transferred_from:'malformed'}},config));assert.deepEqual(webhookOwners({event:{id:'test',type:'TEST'}},config).owners,[]);});
test('expiry, cancellation before expiry, grace and refund come from current subscriber',()=>{assert.equal(subscriberSnapshot(body(),config,now).tier,'plus');const expired=body(now-1000);assert.equal(subscriberSnapshot(expired,config,now).tier,'free');expired.subscriber.entitlements['fixture-plus'].grace_period_expires_date=new Date(now+1000).toISOString();assert.equal(subscriberSnapshot(expired,config,now).tier,'plus');expired.subscriber.subscriptions['fixture-month'].refunded_at=new Date(now).toISOString();assert.equal(subscriberSnapshot(expired,config,now).tier,'free');});
test('sandbox, wrong product, lifetime and malformed/stale response fail closed',()=>{const b=body();assert.equal(subscriberSnapshot(b,{...config,environment:'PRODUCTION'},now).tier,'free');assert.equal(subscriberSnapshot(b,{...config,product_ids:[]},now).tier,'free');b.subscriber.entitlements['fixture-plus'].expires_date=null;assert.equal(subscriberSnapshot(b,config,now).tier,'free');b.request_date_ms=now-700000;assert.throws(()=>subscriberSnapshot(b,config,now));assert.throws(()=>subscriberSnapshot({},config,now));});
test('disabled adapter performs no provider request',async()=>{let calls=0;const admin={from:()=>({select:()=>({single:async()=>({data:{enabled:false},error:null})})})};assert.equal((await reconcileOne(admin,undefined,async()=>{calls++;})).status,'disabled');assert.equal(calls,0);});
test('server fetch only its claimed identity; verified current snapshot and lost token outcomes',async()=>{
 const owner='10000000-0000-0000-0000-000000000001';let finished;const calls=[];
 const admin={from:()=>({select:()=>({single:async()=>({data:config,error:null})})}),rpc:async(name,args)=>{calls.push(name);if(name==='claim_s9_reconcile')return {error:null,data:{status:'claimed',owner_id:owner,claim:'fixture-claim'}};if(name==='finish_s9_reconcile'){finished=args;return {error:null,data:true};}throw Error('unexpected_rpc');}};
 const result=await reconcileOne(admin,'synthetic-key',async(url,options)=>{assert.equal(url,'https://api.revenuecat.com/v1/subscribers/'+owner);assert.equal(options.headers.Authorization,'Bearer synthetic-key');return new Response(JSON.stringify(body()));});
 assert.equal(result.status,'reconciled');assert.equal(finished.owner_id,owner);assert.equal(finished.snapshot.tier,'plus');assert.deepEqual(calls,['claim_s9_reconcile','finish_s9_reconcile']);
});
test('provider failure retains entitlement and schedules retry without client grant',async()=>{
 const calls=[];const admin={from:()=>({select:()=>({single:async()=>({data:config,error:null})})}),rpc:async(name)=>{calls.push(name);return {error:null,data:name==='claim_s9_reconcile'?{status:'claimed',owner_id:'fixture',claim:'fixture'}:true};}};
 assert.equal((await reconcileOne(admin,'synthetic-key',async()=>new Response('{}',{status:429}))).status,'retry_later');assert.deepEqual(calls,['claim_s9_reconcile','fail_s9_reconcile']);
});
