import { useEffect, useRef, useState } from 'react';
import { router } from 'expo-router';
import { Text, View } from 'react-native';
import { Screen, ui } from '@/components/screen';
import { Button } from '@/components/ui/button';
import { Field } from '@/components/rule-fields';
import { DeliveryFields } from '@/components/delivery-fields';
import { useAuth } from '@/lib/auth-context';
import { useLanguage } from '@/lib/i18n';
import { supabase } from '@/lib/supabase';
import { emptyFilters, label, type Area, type Territory } from '@/lib/rules';
import { validPreferences, type DeliveryPreferences } from '@/lib/discovery';
import type { Json } from '@/lib/database.types';
export default function Onboarding(){
 const{t,locale}=useLanguage();const{session,loading}=useAuth();const[step,setStep]=useState(0);const[state,setState]=useState('loading');const[revision,setRevision]=useState(0);const[territories,setTerritories]=useState<Territory[]>([]);const[categories,setCategories]=useState<{code:string;names:Json}[]>([]);const[areas,setAreas]=useState<Area[]>([]);const[codes,setCodes]=useState<string[]>([]);const[search,setSearch]=useState('');const[kind,setKind]=useState<'city'|'country'|'admin'>('city');const[shown,setShown]=useState(12);const[name,setName]=useState('');const[days,setDays]=useState('30');const[timezone,setTimezone]=useState('Europe/Madrid');const[delivery,setDelivery]=useState<DeliveryPreferences>({mode:'manual',time:'18:00',weekdays:[1],days:7,anchor:new Date().toISOString().slice(0,10)});const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const lock=useRef(false);const owner=useRef(session?.user.id);owner.current=session?.user.id;
 useEffect(()=>{let active=true;setState('loading');if(!supabase){setState('error');return;}void Promise.all([supabase.from('territories').select('id,kind,names,country_code,provenance').eq('is_demo',false),supabase.from('categories').select('code,names').order('code')]).then(([ts,cs])=>{if(!active)return;if(ts.error||cs.error)setState('error');else{setTerritories(ts.data);setCategories(cs.data);setState('ready');}});return()=>{active=false;};},[revision]);
 useEffect(()=>{setStep(0);setAreas([]);setCodes([]);setName('');setMessage('');},[session?.user.id]);
 const selectedNames=areas.map(a=>label(territories.find(v=>v.id===a.territory_id)?.names??{},locale));const choices=territories.filter(v=>v.kind===kind&&(label(v.names,locale)+' '+v.country_code).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>label(a.names,locale).localeCompare(label(b.names,locale)));
 function next(){setMessage('');if(step===0&&areas.length===0){setMessage(t('selectTerritory'));return;}if(step===1&&(!Number.isInteger(Number(days))||Number(days)<1||Number(days)>366)){setMessage(t('ruleValidationError'));return;}if(step===2){try{new Intl.DateTimeFormat('en',{timeZone:timezone});if(!validPreferences(delivery))throw Error('Invalid');}catch{setMessage(t('scheduleInvalid'));return;}}setStep(v=>v+1);}
 async function save(){if(!supabase||!session||lock.current)return;const caller=session.user.id;lock.current=true;setBusy(true);setMessage('');try{const doc={name:name.trim()||selectedNames.join(', ').slice(0,100),enabled:true,timezone:timezone.trim(),filters:{...emptyFilters,categories:codes},event_horizon:{kind:'days',days:Number(days)},areas};const{error}=await supabase.rpc('save_s7_rule',{rule_document:doc,delivery_preferences:{...delivery,active:Boolean(delivery.active)} as unknown as Json});if(error)throw error;if(owner.current===caller)router.replace({pathname:'/',params:{mode:'matches'}});}catch{if(owner.current===caller)setMessage(t('ruleValidationError'));}finally{lock.current=false;setBusy(false);}}
 const titles=[t('chooseTerritories'),t('chooseInterests'),t('deliveryPreferences'),t('previewRule')];
 return <Screen title={t('startOnboarding')}>{loading?<Text>{t('loading')}</Text>:!session?<View style={ui.card}><Text style={ui.text}>{t('onboardingIntro')}</Text><Button label={t('signInForRule')} onPress={()=>router.push('/account')}/></View>:state==='loading'?<Text>{t('loading')}</Text>:state==='error'?<View style={ui.card}><Text accessibilityRole="alert">{t('error')}</Text><Button label={t('retry')} onPress={()=>setRevision(v=>v+1)}/></View>:<>
 <Text accessibilityLiveRegion="polite" style={ui.badge}>{step+1} / 4 · {titles[step]}</Text>
 <View style={ui.card}>
 {step===0&&<><Text style={ui.text}>{t('onboardingIntro')}</Text><Text style={ui.muted}>{t('s4Coverage')}</Text><Text style={ui.title}>{selectedNames.join(' · ')||t('selectTerritory')}</Text><View style={ui.row}>{(['city','admin','country'] as const).map(k=><Button key={k} size="sm" label={t(k)} accessibilityState={{selected:kind===k}} variant={kind===k?'default':'outline'} onPress={()=>{setKind(k);setShown(12);setSearch('');}}/>)}</View><Field label={t('territorySearch')} value={search} onChange={v=>{setSearch(v);setShown(12);}}/>{choices.slice(0,shown).map(v=>{const selected=areas.some(a=>a.territory_id===v.id);return <Button key={v.id} label={label(v.names,locale)} accessibilityState={{selected}} variant={selected?'default':'outline'} onPress={()=>{if(selected)setAreas(a=>a.filter(vv=>vv.territory_id!==v.id));else if(areas.length<20)setAreas(a=>[...a,{kind,territory_id:v.id,parameters:{}}]);else setMessage(t('areaLimit'));}}/>;})}{choices.length===0&&<Text>{t('noSearchResults')}</Text>}{choices.length>shown&&<Button label={t('moreTerritories')} variant="link" onPress={()=>setShown(v=>v+12)}/>}<Button label={t('advancedRule')} variant="link" onPress={()=>router.push('/rule/new')}/></>}
 {step===1&&<><Text style={ui.text}>{t('interestsHint')}</Text><View style={ui.row}>{categories.map(c=>{const selected=codes.includes(c.code);return <Button key={c.code} label={label(c.names,locale)} size="sm" accessibilityState={{selected}} variant={selected?'default':'outline'} onPress={()=>setCodes(v=>selected?v.filter(code=>code!==c.code):[...v,c.code])}/>;})}</View><Field label={t('horizonDays')} value={days} numeric onChange={setDays}/><Text style={ui.muted}>{t('horizonSeparate')}</Text></>}
 {step===2&&<DeliveryFields value={delivery} onChange={setDelivery} timezone={timezone} onTimezone={setTimezone}/>}
 {step===3&&<><Field label={t('ruleName')} value={name} onChange={v=>setName(v.slice(0,100))}/><Text style={ui.title}>{selectedNames.join(' · ')}</Text><Text style={ui.text}>{codes.length?codes.map(code=>label(categories.find(v=>v.code===code)?.names??{},locale)).join(' · '):t('allInterests')}</Text><Text style={ui.text}>{t('horizonDays')}: {days} · {timezone}</Text><Text style={ui.text}>{t(delivery.mode==='manual'?'manualMode':delivery.mode==='daily'?'dailyMode':delivery.mode==='weekdays'?'weekdaysMode':'intervalMode')}{delivery.mode!=='manual'?` · ${delivery.time}`:''}</Text>{delivery.mode==='weekdays'&&<Text style={ui.text}>{(delivery.weekdays??[]).map(n=>new Intl.DateTimeFormat(locale,{weekday:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,0,4+n)))).join(' · ')}</Text>}{delivery.mode==='interval'&&<Text style={ui.text}>{t('intervalDays')}: {delivery.days} · {delivery.anchor}</Text>}<Text style={ui.muted}>{t('rulesHint')}</Text><Text style={ui.muted}>{t('s4Coverage')}</Text><Text style={ui.text}>{t('schedulePending')}</Text><Text style={ui.muted}>{t('previewHint')}</Text></>}
 </View>
 {Boolean(message)&&<Text accessibilityRole="alert">{message}</Text>}<View style={ui.row}>{step>0&&<Button label={t('previous')} variant="outline" disabled={busy} onPress={()=>{setStep(v=>v-1);setMessage('');}}/>}{step<3?<Button label={t('next')} onPress={next}/>:<Button label={t('createAndView')} loading={busy} onPress={()=>void save()}/>}</View><Button label={t('cancel')} disabled={busy} variant="link" onPress={()=>router.replace('/')}/>
 </>}</Screen>;
}
